---
- name: User setup
  hosts: all
  remote_user: root

  tasks:
    - name: Add user[s]
      ansible.builtin.user:
        name: ekwisnek
        groups: users,wheel
        state: present
        password: "$6$ETyjf7/rWLfhMk8y$J3kUL2HSSl/dB0cnF9GJsjAnsoZgINDJ2RWGMeuVkbkeBmzzfgizLM1y5KQdB2cZ4H2tV3wLcD7/Oe8FC0rKU0"
    - name: Add ssh key[s]
      ansible.posix.authorized_key:
        user: ekwisnek
        state: present
        key: "{{ lookup('file', '/home/ekwisnek/.ssh/id_ecdsa.pub') }}"
    - name: Add ssh key[s]
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/home/ekwisnek/.ssh/id_ecdsa.pub') }}"

- name: Initialialize primary control plane
  hosts: rke2-prod-cp-01
  become: true

  tasks:
    - name: Make directory
      ansible.builtin.file:
        path: /etc/rancher/rke2/
        state: directory
        mode: "0700"
    - name: Place config
      ansible.builtin.copy:
        src: config/primary_config.yaml
        dest: /etc/rancher/rke2/config.yaml
        mode: "0600"
    - name: Disable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: false
        masked: true

- name: Initialialize additional control plane nodes
  hosts: rke2-prod-cp-02,rke2-prod-cp-03
  become: true

  tasks:
    - name: Make directory
      ansible.builtin.file:
        path: /etc/rancher/rke2/
        state: directory
        mode: "0700"
    - name: Place config
      ansible.builtin.copy:
        src: config/additional_config.yaml
        dest: /etc/rancher/rke2/config.yaml
        mode: "0600"
    - name: Disable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: false
        masked: true

- name: Initialize worker nodes
  hosts: worker
  become: true

  tasks:
    - name: Make directory
      ansible.builtin.file:
        path: /etc/rancher/rke2/
        state: directory
        mode: "0700"
    - name: Place config
      ansible.builtin.copy:
        src: config/worker_config.yaml
        dest: /etc/rancher/rke2/config.yaml
        mode: "0600"
    - name: Disable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: false
        masked: true
    - name: Install disk utilities
      ansible.builtin.package:
        name: nfs-utils,iscsi-initiator-utils
        state: installed
# TODO:
# Enable Kernel auto-patch `dnf kpatch auto`
