---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpret: /usr/bin/python3
    rke2-prod-cp-01:
      ansible_host: 192.168.1.31
    rke2-prod-cp-02:
      ansible_host: 192.168.1.8
    rke2-prod-cp-03:
      ansible_host: 192.168.1.33
    rke2-prod-cp-04:
      ansible_host: 192.168.1.37
    rke2-prod-wk-01:
      ansible_host: 192.168.1.41
    rke2-prod-wk-02:
      ansible_host: 192.168.1.42
    rke2-prod-wk-03:
      ansible_host: 192.168.1.43
    rke2-prod-wk-04:
      ansible_host: 192.168.1.44
    rke2-prod-wk-05:
      ansible_host: 192.168.1.45
    rke2-prod-wk-06:
      ansible_host: 192.168.1.34
    rke2-prod-wk-07:
      ansible_host: 192.168.1.35
    rke2-prod-api-lb:
      ansible_host: 192.168.1.30

lb:
  hosts:
    rke2-prod-api-lb:
      ansible_host: 192.168.1.30

control_plane:
  hosts:
    rke2-prod-cp-01:
      ansible_host: 192.168.1.31
    rke2-prod-cp-02:
      ansible_host: 192.168.1.8
    rke2-prod-cp-03:
      ansible_host: 192.168.1.33
    rke2-prod-cp-04:
      ansible_host: 192.168.1.37

worker:
  hosts:
    rke2-prod-wk-01:
      ansible_host: 192.168.1.41
    rke2-prod-wk-02:
      ansible_host: 192.168.1.42
    rke2-prod-wk-03:
      ansible_host: 192.168.1.43
    rke2-prod-wk-04:
      ansible_host: 192.168.1.44
    rke2-prod-wk-05:
      ansible_host: 192.168.1.45
    rke2-prod-wk-06:
      ansible_host: 192.168.1.34
    rke2-prod-wk-07:
      ansible_host: 192.168.1.35

rke2_cluster:
  children:
    control_plane:
    worker:
