---
apiVersion: v1
kind: ConfigMap
metadata:
  name: semaphore-config
data:
  SEMAPHORE_ADMIN: admin
  SEMAPHORE_ADMIN_NAME: admin
  SEMAPHORE_ADMIN_PASSWORD: password
  SEMAPHORE_DB_USER: semaphore
  SEMAPHORE_DB_PASS: semaphore
  MYSQL_USER: semaphore
  MYSQL_PASSWORD: semaphore
  MYSQL_ROOT_PASSWORD: semaphore
  SEMAPHORE_DB: semaphore
  SEMAPHORE_DB_DIALECT: mysql
  SEMAPHORE_DB_HOST: semaphore-mysql-primary
  SEMAPHORE_DB_PORT: "3306"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: semaphore
  name: semaphore
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: semaphore
  template:
    metadata:
      labels:
        app.kubernetes.io/name: semaphore
    spec:
      containers:
        - name: semaphore
          image: ansiblesemaphore/semaphore
          envFrom:
            - configMapRef:
                name: semaphore-config
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: semaphore
  namespace: semaphore
spec:
  kind: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: semaphore
