kind: Project
apiVersion: management.loft.sh/v1
metadata:
  name: ctrlplane-customer-acme
spec:
  displayName: Team ACME
  owner:
    team: ctrlplane-customer-acme
  quotas:
    project:
      limits.memory: 16Gi
      limits.cpu: '8'
      count/virtualclusterinstances.active: '10'
    user:
      count/virtualclusterinstances: '3'
  allowedClusters:
    - name: loft-cluster # the local k8s cluster. Add additional targets here for dev, stg, prod, shared-services
  allowedTemplates:
    - kind: VirtualClusterTemplate
      group: storage.loft.sh
      name: customer-template-prod
      isDefault: false
    - kind: VirtualClusterTemplate
      group: storage.loft.sh
      name: customer-template-stage
      isDefault: false
    - kind: VirtualClusterTemplate
      group: storage.loft.sh
      name: customer-template-dev
      isDefault: true
    - kind: VirtualClusterTemplate
      group: storage.loft.sh
      name: customer-template-dev-ephemeral
  requireTemplate:
    disabled: false
  members:
    - kind: Team
      group: storage.loft.sh
      name: ctrlplane-customer-acme
      clusterRole: loft-management-project-admin
  access:
    - name: ctrlplane-platform-admin-access
      verbs:
        - get
        - update
        - patch
        - delete
      subresources:
        - '*'
      teams:
        - ctrlplane-customer-acme
  argoCD:
    enabled: true
    cluster: loft-cluster
  namespacePattern:
    virtualCluster: '{{.Values.loft.project}}-v-{{.Values.loft.name}}'