kind: Project
apiVersion: management.loft.sh/v1
metadata:
  name: ctrlplane-platform
spec:
  displayName: Ctrlplane Platform
  owner:
    team: ctrlplane-platform-admins
  quotas:
    project:
      count/virtualclusterinstances.active: '20'
    user:
      count/virtualclusterinstances: '3'
  allowedClusters:
    - name: loft-cluster # the local k8s cluster. Add additional targets here for dev, stg, prod, shared-services
  allowedTemplates:
    - kind: VirtualClusterTemplate
      group: management.loft.sh/v1
      name: platform-template-prod
      isDefault: true
  requireTemplate: {}
  members:
    - kind: Team
      group: storage.loft.sh
      name: ctrlplane-platform-admins
      clusterRole: loft-management-project-admin
  access:
    - name: ctrlplane-platform-admin-access
      verbs:
        - get
        - update
        - patch
        - delete
      subresources:
        - '*'
      teams:
        - ctrlplane-platform-admins
  argoCD:
    enabled: true
    cluster: loft-cluster
  namespacePattern:
    virtualCluster: '{{.Values.loft.project}}-v-{{.Values.loft.name}}'