---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: LoadBalancer
  # ingress_type: Ingress
  # hostname: awx.ctrlplane.net
  postgres_storage_class: rook-ceph-block
