version: "3.7"
services:
  foldingathome:
    image: ghcr.io/linuxserver/foldingathome
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - frontend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - fah_data:/config
volumes:
  fah_data:
networks:
  frontend:
    external: true
