---
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: global-exceptions
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  exceptions:
    - policyName: restrict-apparmor-profiles
      ruleNames:
        - app-armor
        - autogen-app-armor
    - policyName: disallow-host-path
      ruleNames:
        - host-path
        - autogen-host-path
    - policyName: disallow-host-namespaces
      ruleNames:
        - host-namespaces
        - autogen-host-namespaces
    - policyName: disallow-privileged-containers
      ruleNames:
        - privileged-containers
        - autogen-privileged-containers
        - autogen-cronjob-privileged-containers
    - policyName: disallow-capabilities
      ruleNames:
        - adding-capabilities
        - autogen-adding-capabilities
        - autogen-cronjob-adding-capabilities
    - policyName: disallow-host-ports
      ruleNames:
        - host-ports-none
        - autogen-host-ports-none
    - policyName: disallow-selinux
      ruleNames:
        - selinux-type
        - autogen-selinux-type
  match:
    any:
      - resources:
          kinds:
            - Pod
            - DaemonSet
            - ReplicaSet
            - Job
            - CronJob
            - Deployment
          namespaces:
            - kube-system
            - kyverno
            - rook-ceph
