---
- name: User setup
  hosts: all
  remote_user: root

  tasks:
    - name: Add wheel group
      ansible.builtin.group:
        name: wheel
        gid: 1000

    - name: Add user[s]
      ansible.builtin.user:
        name: ekwisnek
        groups: users,sudo
        state: present
        password: "$6$ETyjf7/rWLfhMk8y$J3kUL2HSSl/dB0cnF9GJsjAnsoZgINDJ2RWGMeuVkbkeBmzzfgizLM1y5KQdB2cZ4H2tV3wLcD7/Oe8FC0rKU0"

    - name: Add ssh key[s]
      ansible.posix.authorized_key:
        user: ekwisnek
        state: present
        key: "{{ lookup('file', '/home/ekwisnek/.ssh/id_ecdsa.pub') }}"

    - name: Add ssh key[s]
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/home/ekwisnek/.ssh/id_ecdsa.pub') }}"
