apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongo-client-cert
  namespace: mongodb
spec:
  commonName: mongo-user
  dnsNames:
    - mongo-user
  duration: 2160h0m0s
  issuerRef:
    kind: Issuer
    name: mongodb-in-cluster-ps-psmdb-ca
  secretName: mongo-client-cert
  subject:
    organizations:
      - PSMDB
