---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb-exporter
    spec:
      containers:
        - name: mongodb-exporter
          image: percona/mongodb_exporter:0.39.0
          ports:
            - containerPort: 9216
          args:
            - "--mongodb.uri=mongodb://mongodb_exporter:password@mongodb-in-cluster-ps-rs0.km-mongodb-operator.svc.cluster.local:27017"
            - "--mongodb.collstats-colls=test.test"
            - "--log.level=debug"
            - "--collect-all"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  annotations:
    metrics.agent.grafana.com/scrape: "true"
    probes.agent.grafana.com/probe: "true"
    probes.agent.grafana.com/module: "http_2xx"
    probes.agent.grafana.com/port: "9216"
    probes.agent.grafana.com/path: "/metrics"
spec:
  selector:
    app.kubernetes.io/name: mongodb-exporter
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9216
      targetPort: 9216
