---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: mongodb-post-creation-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  template:
    spec:
      serviceAccountName: default
      containers:
        - name: mongo-client-init-database
          image: percona/percona-server-mongodb:6.0.11
          command:
            - "mongosh"
            - "mongodb+srv://$(MONGODB_DATABASE_ADMIN_USER):$(MONGODB_DATABASE_ADMIN_PASSWORD)@mongodb-in-cluster-ps-rs0.mongodb.svc.cluster.local/admin?replicaSet=rs0&ssl=false"
            - "--eval"
            - "load('/tmp/init-database.js')"
          env:
            - name: MONGODB_DATABASE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGODB_DATABASE_ADMIN_PASSWORD
                  name: mongodb-in-cluster-ps-secrets
            - name: MONGODB_DATABASE_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: MONGODB_DATABASE_ADMIN_USER
                  name: mongodb-in-cluster-ps-secrets
          volumeMounts:
            - name: init-scripts
              mountPath: /tmp
        - name: mongo-client-init-users
          image: percona/percona-server-mongodb:6.0.11
          command:
            - "mongosh"
            - "mongodb+srv://$(MONGODB_USER_ADMIN_USER):$(MONGODB_USER_ADMIN_PASSWORD)@mongodb-in-cluster-ps-rs0.mongodb.svc.cluster.local/admin?replicaSet=rs0&ssl=false"
            - "--eval"
            - "load('/tmp/init-users.js')"
          env:
            - name: MONGODB_USER_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGODB_USER_ADMIN_PASSWORD
                  name: mongodb-in-cluster-ps-secrets
            - name: MONGODB_USER_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: MONGODB_USER_ADMIN_USER
                  name: mongodb-in-cluster-ps-secrets
          volumeMounts:
            - name: init-scripts
              mountPath: /tmp
      volumes:
        - name: init-scripts
          configMap:
            name: post-sync-cm
      restartPolicy: Never
  backoffLimit: 3
