---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: mongodb-user-creation-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: default
      containers:
        - name: mongo-client
          image: percona/percona-server-mongodb:6.0.11
          command:
            - "mongosh"
            - "mongodb+srv://databaseAdmin:wH4qlp7HPOT17iZT@mongodb-in-cluster-ps-rs0.mongodb.svc.cluster.local/admin?replicaSet=rs0&ssl=false"
            - "--eval"
            - "use test-db"
            - "mongosh"
            - "mongodb+srv://userAdmin:DWNiVxfa5lygpjb2I@mongodb-in-cluster-ps-rs0.mongodb.svc.cluster.local/admin?replicaSet=rs0&ssl=false"
            - "--eval"
            - "db.getSiblingDB('$external').runCommand({createUser: 'CN=app-user', roles: [{ role: 'dbOwner', db: 'test-db' }], mechanisms:['MONGODB-X509']})"
      restartPolicy: Never
  backoffLimit: 3
