---
- name: Provision Talos Linux VMs on Proxmox
  hosts: localhost
  gather_facts: false
  vars_files:
    - proxmox-credentials.yaml
    - virtual-machines.yaml

  vars:
    proxmox_api_user: "root@pam"
    proxmox_api_password: "{{ proxmox_root_password }}"
    proxmox_api_host: "192.168.1.94"
    vm_count: 6
    base_ip_address: "192.168.1.201"
    base_mac_address: "52:54:00:11:22:"
    proxmox_node: "prox-04"

  tasks:
    # - name: Get Proxmox CSRF token
    #   uri:
    #     url: "https://{{ proxmox_api_host }}/api2/json/access/ticket"
    #     method: POST
    #     body_format: form-urlencoded
    #     body:
    #       username: "{{ proxmox_api_user }}"
    #       password: "{{ proxmox_api_password }}"
    #     status_code: 200
    #     validate_certs: no
    #   register: proxmox_ticket

    - name: Create Talos Linux VMs
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        vmid: "{{ 200 + item | int }}"
        name: "talos-vm{{ item }}"
        ostype: "l26"
        scsihw: virtio-scsi-pci
        ide:
          ide0: "{{ proxmox_api_host }}/templates/iso/talos-live-installer.iso,media=cdrom"
        sata:
          sata0: "{{ proxmox_api_host }}/storage/local-lvm:{{ proxmox_api_host }}/templates/cache:64G"
        cores: 2
        sockets: 1
        memory: 2048
        net:
          net0: "virtio,bridge=vmbr0,rate=1000,model={{ base_mac_address }}{{ '%02x'|format(item | int) }}"
        onboot: yes
        state: present
        node: "{{ proxmox_node }}"
      with_sequence:
        start=0 end={{ vm_count - 1 }}

        # when: proxmox_ticket.json.ticket is defined

      # - name: Set Fixed IP Addresses for Talos Linux VMs
      #   community.general.proxmox_vm_config:
      #     api_user: "{{ proxmox_api_user }}"
      #     api_password: "{{ proxmox_api_password }}"
      #     api_host: "{{ proxmox_api_host }}"
      #     vmid: "{{ 200 + loop.index0 }}"
      #     data:
      #       net0: "virtio,bridge=vmbr0,mac={{ base_mac_address }}{{ '%02x'|format(loop.index0) }},ip={{ base_ip_address | ipmath(loop.index0) }}/24,gw=192.168.1.1"
      #   loop: "{{ range(vm_count) }}"
      #   when: proxmox_ticket.json.ticket is defined
