---
- name: Virtual Machine Creation
  hosts: localhost
  vars_files:
    - proxmox-credentials.yaml
    - virtual-machines.yaml

  vars:
    update: false

  tasks:
    - name: Stop worker nodes
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: "{{ proxmox_root_password }}"
        api_host: 192.168.1.94
        vmid: "{{ item.vmid }}"
        state: stopped
        node: prox-04
      loop: "{{ virtual_machines.workers }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Stop control plane nodes
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: "{{ proxmox_root_password }}"
        api_host: 192.168.1.94
        vmid: "{{ item.vmid }}"
        name: "{{ item.name }}"
        state: stopped
        node: prox-04
      loop: "{{ virtual_machines.control_plane }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Delete worker nodes
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: "{{ proxmox_root_password }}"
        api_host: 192.168.1.94
        vmid: "{{ item.vmid }}"
        state: absent
        node: prox-04
      loop: "{{ virtual_machines.workers }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Delete control plane nodes
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: "{{ proxmox_root_password }}"
        api_host: 192.168.1.94
        vmid: "{{ item.vmid }}"
        name: "{{ item.name }}"
        state: absent
        node: prox-04
      loop: "{{ virtual_machines.control_plane }}"
      loop_control:
        label: "{{ item.name }}"
