---
redis-ha:
  enabled: true
controller:
  replicas: 3
server:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 7
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 7
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
  resources:
    limits:
      cpu: 400m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
applicationSet:
  replicaCount: 2
configs:
  cm:
    create: false
  rbac:
    create: false