---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: "default"
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: authenik-postgresql
      jqPathExpressions:
        - '.data."postgres-password"'
  sources:
    - repoURL: "https://charts.goauthentik.io"
      targetRevision: 2024.6.0
      chart: authentik
      helm:
        valueFiles:
          - $values/rke2/kubernetes/core/authentik/values.yaml       
    - repoURL: "https://github.com/ekwisnek/selfhosted"
      ref: values
    # - repoURL: "https://percona.github.io/percona-helm-charts/"
    #   chart: pg-db
    #   targetRevision: 2.4.0
    #   helm:
    #     valueFiles:
    #       - $values/rke2/kubernetes/core/authentik/postgres-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true