---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.jetstack.io"
    targetRevision: v1.13.1
    chart: cert-manager
    helm:
      valuesObject:
        featureGates: "AdditionalCertificateOutputFormats=true"
        webhook:
          featureGates: "AdditionalCertificateOutputFormats=true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
