---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: falco-falcosidekick-ui-redis
      jqPathExpressions:
        - ".spec.volumeClaimTemplates[]?"
  project: default
  sources:
    - repoURL: "https://falcosecurity.github.io/charts"
      targetRevision: 4.14.2
      chart: falco
      helm:
        valueFiles:
          - $values/rke2/kubernetes/core/falco/values.yaml       
    - repoURL: "https://github.com/ekwisnek/selfhosted"
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true