---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:ekwisnek/selfhosted.git"
    targetRevision: HEAD
    path: rke2/kubernetes/core/monitoring/grafana-agent
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
