---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  sources:
    - path: rke2/kubernetes/core/kyverno/policies
      repoURL: "git@github.com:ekwisnek/selfhosted.git"
    - repoURL: "https://kyverno.github.io/kyverno"
      targetRevision: 3.0.6
      chart: kyverno
      helm:
        valuesObject:
          admissionController:
            replicas: 3
          backgroundController:
            replicas: 2
            extraArgs:
              skipResourceFilters: false
          cleanupController:
            replicas: 2
          reportsController:
            replicas: 2
          config:
            resourceFiltersExcludeNamespaces:
              - kube-system
              - kyverno
            webhooks:
              - namespaceSelector:
                  matchExpressions:
                    - key: kubernetes.io/metadata.name
                      operator: NotIn
                      values:
                        - kube-system
                        - kyverno
              - objectSelector:
                  matchExpressions:
                    - key: webhooks.kyverno.io/exclude
                      operator: DoesNotExist
            features:
              backgroundScan:
                skipResourceFilters: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
