---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: loki-backend
      jqPathExpressions:
        - ".spec.persistentVolumeClaimRetentionPolicy?"
    - group: apps
      kind: StatefulSet
      name: loki-backend
      jqPathExpressions:
        - ".spec.volumeClaimTemplates[]?"
    - group: monitoring.grafana.com/v1alpha1
      kind: PodLogs
      name: loki
      jqPathExpressions:
        - ".spec.relabelings[]?"
  project: default
  sources:
    - repoURL: "git@github.com:ekwisnek/selfhosted.git"
      targetRevision: HEAD
      ref: values
    - repoURL: "https://grafana.github.io/helm-charts"
      targetRevision: 5.36.1
      chart: loki
      helm:
        valueFiles:
          - $values/rke2/kubernetes/core/monitoring/loki-prod-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
