---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "git@github.com:ekwisnek/selfhosted.git"
      targetRevision: HEAD
      ref: values
    - repoURL: "https://grafana.github.io/helm-charts"
      targetRevision: 5.36.1
      chart: loki
      helm:
        valueFiles:
          - $values/kubernetes/core/monitoring/loki-prod-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
