---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-platform
  namespace: argocd
spec:
  project: "default"
  syncPolicy:
    applicationsSync: create-update
    preserveResourcesOnDeletion: true
  destination:
    namespace: vcluster-platform-1
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://charts.loft.sh"
    targetRevision: 4.2.3
    chart: vcluster-platform
    helm:
      values: |
        admin:
          create: true
          username: admin
          password: ""
          email: info@ctrlplane.net
        replicaCount: 3
        config:
          costControl:
            enabled: false
          loftHost: "vcluster-platform.ctrlplane.net"
        image: ghcr.io/loft-sh/vcluster-platform:4.2.3
        ingress:
          enabled: true
          host: "vcluster-platform.ctrlplane.net"
          name: vcluster-platform-ingress
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
          path: /
          tls:
            enabled: true
            secret: vcluster-platform-tls
        env:
          DEFAULT_VCLUSTER_CHART_VERSION: 0.24.1
          DISABLE_LOFT_ROUTER: true
          LICENSE_KEY: ""
        serviceMonitor:
          enabled: true
        tls:
          enabled: true
          secret: vcluster-platform-tls
          crtKey: tls.crt
          keyKey: tls.key
        agentValues:
          resources:
            requests:
              memory: 256Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true