alertmanager:
  enabled: false
server:
  extraScrapeConfigs:
    - job_name: vault
      metrics_path: /v1/sys/metrics
      params:
        format: ['prometheus']
      scheme: https
      tls_config:
          insecure_skip_verify: true
      authorization:
        credentials: ''
      static_configs:
      - targets: ['vault-test.kites-test.km.spaceforce.mil']