---
server:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt
    ingressClassName: nginx
    hosts:
      - host: vault.ctrlplane.net
    paths: /
    tls:
      - hosts:
          - vault.ctrlplane.net
          - www.vault.ctrlplane.net
        secretName: vault-ctrlplane-net-web-cert
  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: ceph-block
  auditStorage:
    enabled: true
    size: 10Gi
    storageClass: ceph-block
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
ui:
  enabled: true
