apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: km-topic
  labels:
    strimzi.io/cluster: km-kafka
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
