apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: example-customer-vcluster
  labels:
    env: dev
    team: ctrlplane-customer-acme
spec:
  displayName: example-customer-vcluster
  owner:
    team: ctrlplane-customer-acme
  templateRef:
    name: customer-template-dev
    version: 1.0.0
  clusterRef:
    cluster: loft-cluster
    namespace: example-customer-vcluster-namespace
    virtualCluster: example-customer-vcluster
  parameters: |
    k8sVersion: v1.31.6
  networkPeer: true