---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: NodePort
  image: quay.io/ansible/awx
  image_version: 23.5.0
  ee_images:
    - name: awx-ee
      image: quay.io/ansible/awx-ee:23.5.0
  ingress_type: Ingress
  ingress_tls_secret: awx-ctrlplane-net-web-cert
  ingress_path: /
  ingress_annotations: |
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
  hostname: awx.ctrlplane.net
  postgres_storage_class: rook-ceph-block
  postgres_image: postgres:13
  redis_image: docker.io/redis
  redis_image_version: 7.2.3
