version: "3.7"
services:
  swag:
    image: linuxserver/swag:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=kwisnet.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=f760af65-0609-4895-997c-78b1e454cd31
      - EMAIL=ekwisnek@something.com
    volumes:
      - /bricks/brick1/gv0/swarm/swag:/config
    configs:
      - source: code-server.subdomain.conf
        target: /config/nginx/proxy-confs/code-server.subdomain.conf
      - source: grafana.subdomain.conf
        target: /config/nginx/proxy-confs/grafana.subdomain.conf
      - source: portainer.subdomain.conf
        target: /config/nginx/proxy-confs/portainer.subdomain.conf
      - source: openvpn-as.subdomain.conf
        target: /config/nginx/proxy-confs/openvpn-as.subdomain.conf
      - source: pihole.subdomain.conf
        target: /config/nginx/proxy-confs/pihole.subdomain.conf
    networks:
      - frontend
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
networks:
  frontend:
    external: true
configs:
  code-server.subdomain.conf:
    external: true
  grafana.subdomain.conf:
    external: true
  openvpn-as.subdomain.conf:
    external: true
  pihole.subdomain.conf:
    external: true
  portainer.subdomain.conf:
    external: true
