---
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: cilium-host-ns-exception
  namespace: kube-system
spec:
  exceptions:
    - policyName: disallow-host-namespaces
      ruleNames:
        - host-namespaces
        - autogen-host-namespaces
  match:
    any:
      - resources:
          kinds:
            - Pod
            - DaemonSet
            - ReplicaSet
          namespaces:
            - kube-system
          names:
            - important-tool*
