apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: authentik-postgres
spec:
  # image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.3-2
  postgresVersion: 15
  instances:
    - name: authentik-postgres
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 5Gi
  # backups:
  #   pgbackrest:
  #     # image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.45-2
  #     repos:
  #     - name: repo1
  #       volume:
  #         volumeClaimSpec:
  #           accessModes:
  #           - "ReadWriteOnce"
  #           resources:
  #             requests:
  #               storage: 5Gi
  #     - name: repo2
  #       volume:
  #         volumeClaimSpec:
  #           accessModes:
  #           - "ReadWriteOnce"
  #           resources:
  #             requests:
  #               storage: 5Gi
  proxy:
    pgBouncer:
      # image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.19-2