replicaCount: 3
image:
  repository: percona/percona-server-mongodb-operator
  tag: 1.15.0
  pullPolicy: IfNotPresent
disableTelemetry: true
watchAllNamespaces: true
rbac:
  create: true
serviceAccount:
  create: true
podAnnotations:
  {}
  # prometheus.io/scrape: "true"
  # prometheus.io/port: "8080"
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 2
  runAsGroup: 2
  fsGroup: 2
  fsGroupChangePolicy: "OnRootMismatch"
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
env:
  resyncPeriod: 5s
  logVerbose: false
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
