---
redis-ha:
  enabled: true
controller:
  replicas: 1
server:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 7
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 64Mi
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 7
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 64Mi
applicationSet:
  replicaCount: 2
