---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eraser
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://eraser-dev.github.io/eraser/charts"
    targetRevision: 1.2.3
    chart: eraser
  destination:
    server: "https://kubernetes.default.svc"
    namespace: eraser
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
