---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://kyverno.github.io/kyverno"
    targetRevision: 3.0.6
    chart: kyverno
    helm:
      valuesObject:
        admissionController:
          replicas: 3
          # container:
          #   extraArgs:
          #     - --enablePolicyException=true
        backgroundController:
          replicas: 2
        cleanupController:
          replicas: 2
        reportsController:
          replicas: 2
        config:
          webhooks:
            # Exclude namespaces
            - namespaceSelector:
                matchExpressions:
                  - key: kubernetes.io/metadata.name
                    operator: NotIn
                    values:
                      - kube-system
                      - kyverno
            # Exclude objects
            - objectSelector:
                matchExpressions:
                  - key: webhooks.kyverno.io/exclude
                    operator: DoesNotExist
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
