---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "git@github.com:ekwisnek/selfhosted.git"
      targetRevision: HEAD
      ref: values
    - repoURL: "https://grafana.github.io/helm-charts"
      targetRevision: 5.1.2
      chart: mimir-distributed
      helm:
        valueFiles:
          - $values/kubernetes/core/monitoring/mimir-prod-values.yaml
    - repoURL: "https://grafana.github.io/helm-charts"
      targetRevision: 5.36.1
      chart: loki
      helm:
        valueFiles:
          - $values/kubernetes/core/monitoring/loki-prod-values.yaml
    - repoURL: "https://grafana.github.io/helm-charts"
      targetRevision: 7.0.2
      chart: grafana
      helm:
        valueFiles:
          - $values/kubernetes/core/monitoring/grafana-prod-values.yaml
    - repoURL: "https://charts.min.io"
      targetRevision: 5.0.14
      chart: minio
      helm:
        valueFiles:
          - $values/kubernetes/core/monitoring/loki-prod-values.yaml
    - repoURL: "git@github.com:ekwisnek/selfhosted.git"
      targetRevision: HEAD
      path: kubernetes/core/monitoring/additional-resources
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
