apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apicurio-registry-operator
  namespace: argocd
spec:
  project: "default"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: apicurio-registry-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    repoURL: "git@github.com:ekwisnek/selfhosted.git"
    path: rke2/kubernetes/apps/apicurio
