apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden-cli
  namespace: argocd
spec:
  project: "default"
  source:
    repoURL: "https://github.com/ekwisnek/selfhosted"
    directory:
      recurse: true
      exclude: credential-secret.yaml
    path: rke2/kubernetes/apps/external-secrets-operator/bitwarden
  destination:
    server: "https://kubernetes.default.svc"
    namespace: bitwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true