apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-operator
  namespace: argocd
spec:
  project: "default"
  sources:
    - repoURL: "https://mysql.github.io/mysql-operator"
      chart: mysql-operator
      targetRevision: 2.2.1
      helm:
        valuesObject: |
          envs:
            k8sClusterDomain: cluster.local
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mysql-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true