apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-operator
  namespace: argocd
spec:
  project: "default"
  # ignoreDifferences:
  #   - group: mysql.oracle.com
  #     kind: CustomResourceDefinition
  #     name: innodbclusters.mysql.oracle.com
  #     jqPathExpressions:
  #       - "spec.additionalPrinterColumns.schema.openAPIV3Schema.properties.spec.properties.keyring.properties.oci.properties.endpoints.description"
  sources:
    - repoURL: "https://mysql.github.io/mysql-operator"
      chart: mysql-operator
      targetRevision: 2.2.2
      helm:
        values: |
          envs:
            k8sClusterDomain: cluster.local
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mysql-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true