apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
spec:
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: nats
      jqPathExpressions:
        - ".spec.volumeClaimTemplates[]?"
  project: "default"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nats
  sources:
    - repoURL: "https://nats-io.github.io/k8s/helm/charts/"
      chart: nats
      targetRevision: 1.2.4
      helm:
        valueFiles:
          - $values/rke2/kubernetes/apps/nats/values.yaml
    - repoURL: "https://github.com/ekwisnek/selfhosted"
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
