apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: percona-postgres-operator
  namespace: argocd
spec:
  project: "default"
  sources:
    - repoURL: "https://github.com/ekwisnek/selfhosted"
      path: rke2/kubernetes/apps/percona-postgres-operator
      ref: values
    - repoURL: "https://percona.github.io/percona-helm-charts/"
      chart: pg-operator
      targetRevision: 2.3.6
      helm:
        valueFiles:
          - $values/rke2/kubernetes/apps/percona-postgres-operator/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: percona-postgres-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true