apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: percona-postgres-operator
  namespace: argocd
spec:
  project: "default"
  source:
    repoURL: "git@github.com:ekwisnek/selfhosted.git"
    path: rke2/kubernetes/apps/percona/postgres-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgres-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
