apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-pg
  namespace: argocd
spec:
  project: "default"
  source:
    repoURL: "https://percona.github.io/percona-helm-charts"
    targetRevision: 2.2.7
    chart: pg-db
  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
