---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mongodb
  namespace: argocd
  labels:
    app.kubernetes.io/component: mongodb
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            storageclass: ceph-block
            url: https://kubernetes.default.svc
            # dbname: test-db
            # dbuser: app-user
  template:
    metadata:
      name: "mongodb-{{cluster}}"
      labels:
        app.kubernetes.io/component: mongodb
        app.kubernetes.io/name: "mongodb-{{cluster}}"
    spec:
      project: "default"
      sources:
        - repoURL: "https://github.com/ekwisnek/selfhosted"
          targetRevision: HEAD
          ref: values
        - chart: psmdb-db
          repoURL: https://percona.github.io/percona-helm-charts/
          targetRevision: 1.14.3
          helm:
            valueFiles:
              - $values/rke2/kubernetes/apps/percona-mongodb/values.yaml
        - repoURL: "https://github.com/ekwisnek/selfhosted"
          targetRevision: HEAD
          path: rke2/kubernetes/apps/percona-mongodb/additional-resources
      destination:
        server: "{{url}}"
        namespace: mongodb
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
