---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: percona-mongodb-operator
  namespace: argocd
  labels:
    app.kubernetes.io/component: mongodb-operator
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            storageclass: rook-ceph-block
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "mongodb-operator-{{cluster}}"
      labels:
        app.kubernetes.io/component: mongodb-operator
        app.kubernetes.io/name: "mongodb-operator-{{cluster}}"
    spec:
      project: "default"
      sources:
        - repoURL: "git@github.com:ekwisnek/selfhosted.git"
          targetRevision: HEAD
          ref: values
        - chart: psmdb-operator
          repoURL: https://percona.github.io/percona-helm-charts/
          targetRevision: 1.14.3
          helm:
            valueFiles:
              - $values/kubernetes/apps/percona-mongodb-operator/values.yaml
      destination:
        server: "{{url}}"
        namespace: percona-mongodb-operator
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
