apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semaphore
  namespace: argocd
spec:
  project: "default"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: semaphore
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: "git@github.com:ekwisnek/selfhosted.git"
      targetRevision: main
      ref: values
    - repoURL: "https://charts.bitnami.com/bitnami"
      chart: mysql
      targetRevision: 9.14.1
      helm:
        valueFiles:
          - $values/kubernetes/apps/semaphore/values.yaml
    - repoURL: "git@github.com:ekwisnek/selfhosted.git"
      targetRevision: main
      path: $values/kubernetes/apps/semaphore
