apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  namespace: argocd
spec:
  project: "default"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: awx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: "https://ansible.github.io/awx-operator/"
      chart: awx-operator
      targetRevision: 2.7.1
