apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argocd
spec:
  project: "default"
  source:
    repoURL: "git@github.com:ekwisnek/selfhosted.git"
    path: kubernetes/apps/awx
  destination:
    server: "https://kubernetes.default.svc"
    namespace: awx
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true