apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argocd
spec:
  project: "default"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: awx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: "git@github.com:ekwisnek/selfhosted.git"
    path: kubernetes/apps/awx
