---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mongodb
  namespace: argocd
  labels:
    app.kubernetes.io/component: mongodb
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            storageclass: rook-ceph-block
            url: https://kubernetes.default.svc
            dbname: test
            dbuser: app-user
  template:
    metadata:
      name: "mongodb-{{cluster}}"
      labels:
        app.kubernetes.io/component: mongodb-operator
        app.kubernetes.io/name: "mongodb-{{cluster}}"
    spec:
      project: "default"
      sources:
        - repoURL: "git@github.com:ekwisnek/selfhosted.git"
          targetRevision: HEAD
          ref: values
        - chart: psmdb-db
          repoURL: https://percona.github.io/percona-helm-charts/
          targetRevision: 1.14.3
          helm:
            valueFiles:
              - $values/kubernetes/apps/percona-mongodb/values.yaml
        # - repoURL: "git@github.com:ekwisnek/selfhosted.git"
        #   targetRevision: HEAD
        #   path: kubernetes/apps/percona-mongodb
      destination:
        server: "{{url}}"
        namespace: mongodb
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
  postSync:
    - name: add-mongodb-user
      hookType: Job
      manifest: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          generateName: mongodb-database-creation-
          annotations:
            argocd.argoproj.io/hook: PostSync
            argocd.argoproj.io/hook-delete-policy: HookSucceeded
        spec:
          template:
            spec:
              serviceAccountName: default
              containers:
                - name: mongo-client
                  image: percona/percona-server-mongodb:5.0.21
                  command:
                    - "mongo"
                    - "mongodb+srv://userAdmin:DWNiVxfa5lygpjb2I@mongodb-in-cluster-ps-rs0.mongodb.svc.cluster.local/admin?replicaSet=rs0&ssl=false"
                    - "--eval"
                    - "db.createUser({user: \"{{dbuser}}\", pwd: 'password', roles: [{db: \"{{dbname}}\", role: 'readWrite' }], mechanisms: ['SCRAM-SHA-1']})"
              restartPolicy: Never
          backoffLimit: 2
