---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.25.0
      helm:
        valueFiles:
          - $values/kubernetes/apps/vault/values.yaml
    - repoURL: "git@github.com:ekwisnek/selfhosted.git"
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: "admissionregistration.k8s.io"
      kind: "MutatingWebhookConfiguration"
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
